version: '2'
services:
    fsjda-app:
        image: fsjda
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://fsjda-mysql:3306/fsjda?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    fsjda-mysql:
        extends:
            file: mysql.yml
            service: fsjda-mysql
